#!/usr/bin/env ruby
output = `./cucumber.py sample.feature`

if $? == 0
  File.open("cucumber_on_github.html", "w") do |f|
    f << '<html><head><title>Gherkin with Github colors</title><link rel="stylesheet" href="github.css"></head><body>'
    f<< output
    f << '</body></html>'
  end
  `open cucumber_on_github.html`
else
  exit $?
end


